workshop/petstagram/petstagram/main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from petstagram.main.views.generic import HomeView, DashboardView
from petstagram.main.views.pets import CreatePetView, EditPetView, DeletePetView
from petstagram.main.views.photos import like_pet, CreatePetPhotoView, PetPhotoDetails, EditPetPhotoView, \
    DeletePetPhotoView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('401/', TemplateView.as_view(template_name='main/401.html'), name='401'),


    path('pet/add/', CreatePetView.as_view(), name='create pet'),
    path('pets/edit/<int:pk>/', EditPetView.as_view(), name='edit pet'),
    path('pets/delete/<int:pk>/', DeletePetView.as_view(), name='delete pet'),

    path('photo/details/<int:pk>/', PetPhotoDetails.as_view(), name='pet photo details'),
    path('photo/like/<int:pk>', like_pet, name='like photo'),
    path('photo/add/', CreatePetPhotoView.as_view(), name='create pet photo'),
    path('photo/edit/<int:pk>/', EditPetPhotoView.as_view(), name='edit pet photo'),
    path('photo/delete/<int:pk>/', DeletePetPhotoView.as_view(), name='delete pet photo')
]

workshop/petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.main.urls')),
    path('accounts/', include('petstagram.auth_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

workshop/petstagram/petstagram/auth_app/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.validators import MinLengthValidator
from django.db import models

from petstagram.auth_app.managers import PetstagramUserManager
from petstagram.common.validators import only_letters_validator

'''
1. Create Model.
2. Configure Model in settings.py
3. Create user manager 
'''


class PetstagramUser(AbstractBaseUser, PermissionsMixin):
        USERNAME_MAX_LENGTH = 25
        username = models.CharField(
            max_length=USERNAME_MAX_LENGTH,
            unique=True,
        )
        date_joined = models.DateTimeField(auto_now_add=True)
        is_staff = models.BooleanField(default=False)

        USERNAME_FIELD = 'username'

        objects = PetstagramUserManager()


class Profile(models.Model):
    FIRST_NAME_MIN_LENGTH = 2
    FIRST_NAME_MAX_LENGTH = 30
    LAST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 30

    GENDER_MALE = ('Male', 'Male')
    GENDER_FEMALE = ('Female', 'Female')
    GENDER_DO_NOT_SHOW = ('Do not show', 'Do not show')
    GENDERS = [GENDER_FEMALE, GENDER_MALE, GENDER_DO_NOT_SHOW]
    # id/pk by default
    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(FIRST_NAME_MIN_LENGTH),
            only_letters_validator,
        ),
    )
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(LAST_NAME_MIN_LENGTH),
            only_letters_validator,
        )
    )
    picture = models.URLField()
    birth_date = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    gender = models.CharField(
        max_length=max(len(x) for x, _ in GENDERS),
        choices=GENDERS,
        default=GENDER_DO_NOT_SHOW,
    )
    user = models.OneToOneField(
        get_user_model(),
        on_delete=models.CASCADE,
        primary_key=True
    )

workshop/petstagram/petstagram/main/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models

from petstagram.common.validators import file_max_size, MinDateValidator

UserModel = get_user_model()


# Create your models here.

class Pet(models.Model):
    # Constants
    NAME_MAX_LENGTH = 30
    CAT = 'Cat'
    DOG = 'Dog'
    BUNNY = 'Bunny'
    PARROT = 'Parrot'
    FISH = 'Fish'
    OTHER = 'Other'
    MIN_DATE = datetime.date(1920, 1, 1)
    TYPES = [(x, x) for x in (CAT, DOG, BUNNY, PARROT, FISH, OTHER)]
    # fields
    name = models.CharField(
        max_length=NAME_MAX_LENGTH,
        unique=True,
    )
    type = models.CharField(
        choices=TYPES,
        max_length=max(len(x) for (x, _) in TYPES)
    )
    birth_date = models.DateField(
        null=True,
        blank=True,
        validators=(
            MinDateValidator(MIN_DATE),
        )
    )
    # relations one-to-one,one-to-many,many-to-many
    # one to many one user can have many pets but every pet 1 user
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    @property
    def age(self):
        return datetime.datetime.now().year - self.birth_date.year

    class Meta:
        # makes a unique pairing u can have multiple same pet names
        # with different owners but 1 owner has unique pets
        unique_together = ('user', 'name')


class PetPhoto(models.Model):
    photo = models.ImageField(
        validators=(
            file_max_size,
        )
    )
    # TODO validate at least 1 pet
    tagged_pets = models.ManyToManyField(
        Pet,
        null=False,
    )
    user = models.ForeignKey(UserModel,
                             on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

workshop/petstagram/petstagram/main/forms/pet_forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError

from petstagram.common.helpers import BootStrapFormMixin
from petstagram.main.models import Pet, PetPhoto


class CreatePetForm(BootStrapFormMixin, forms.ModelForm):
    MIN_DATE_OF_BIRTH = date(1920, 1, 1)
    MAX_DATE_OF_BIRTH = date.today()

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self._init_bootstrap_form_controls()

    def save(self, commit=True):
        pet = super().save(commit=False)
        pet.user = self.user
        if commit:
            pet.save()
        return pet

    def clean_birth_date(self):
        birth_date = self.cleaned_data['birth_date']
        if birth_date is not None:
            if birth_date < self.MIN_DATE_OF_BIRTH or birth_date > self.MAX_DATE_OF_BIRTH:
                raise ValidationError('Date of birth out of range')

    class Meta:
        model = Pet
        fields = ('name', 'type', 'birth_date')
        widgets = {
            'name': forms.TextInput(
                attrs={"placeholder": "Enter Pet name"
                       }),
        }


class DeletePetForm(BootStrapFormMixin, forms.ModelForm):
    def save(self, commit=True):
        # self.instance = profile
        PetPhoto.objects.filter(tagged_pets=self.instance.pk).delete()
        self.instance.delete()
        return self.instance

    class Meta:
        model = Pet
        fields = ()

workshop/petstagram/petstagram/main/forms/photo_forms.py
from django import forms

from petstagram.common.helpers import BootStrapFormMixin
from petstagram.main.models import PetPhoto


class CreatePhotoForm(BootStrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = PetPhoto
        fields = ('photo', 'description', 'tagged_pets')

        widgets = {
            'photo': forms.FileInput(
                attrs={'class': 'form-control-file'}
            ),
            'description': forms.Textarea(
                attrs={'rows': 3, 'placeholder': 'Enter Description'}
            )
        }


class EditPhotoForm(BootStrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    class Meta:
        model = PetPhoto
        fields = ('description', 'tagged_pets')

        widgets = {
            'description': forms.Textarea(
                attrs={'rows': 3, 'placeholder': 'Enter Description'}
            )
        }


class DeletePhotoForm(forms.ModelForm):
    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = PetPhoto
        fields = ()

workshop/petstagram/petstagram/main/views/generic.py
from django.views.generic import TemplateView, ListView

from petstagram.common.view_mixins import RedirectToDashboard
from petstagram.main.models import PetPhoto


class HomeView(RedirectToDashboard,TemplateView):
    template_name = 'main/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['hide_additional_nav_items'] = True
        return context




class DashboardView(ListView):
    model = PetPhoto
    template_name = 'main/dashboard.html'
    context_object_name = 'pets'

workshop/petstagram/petstagram/main/views/pets.py
from django.views.generic import CreateView, UpdateView, DeleteView

from petstagram.main.forms.pet_forms import CreatePetForm, DeletePetForm


class CreatePetView(CreateView):
    template_name = 'main/pet_create.html'
    form_class = CreatePetForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    # def form_valid(self, form):
    #     user = self.request.user
    #     return super().form_valid(form)


class EditPetView(UpdateView):
    template_name = 'main/pet_edit.html'
    form_class = CreatePetForm


class DeletePetView(DeleteView):
    template_name = 'main/pet_delete.html'
    form_class = DeletePetForm

workshop/petstagram/petstagram/main/views/photos.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from petstagram.main.forms.photo_forms import CreatePhotoForm, DeletePhotoForm, EditPhotoForm
from petstagram.main.models import PetPhoto


def like_pet(request, pk):
    pet_photo = PetPhoto.objects.get(pk=pk)
    pet_photo.likes += 1
    pet_photo.save()
    return redirect('pet photo details', pk)


class PetPhotoDetails(DetailView, LoginRequiredMixin):
    model = PetPhoto
    template_name = 'main/photo_details.html'
    context_object_name = 'pet_photo'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.prefetch_related('tagged_pets')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_owner'] = self.object.user == self.request.user
        return context


class CreatePetPhotoView(CreateView, LoginRequiredMixin):
    model = PetPhoto
    template_name = 'main/photo_create.html'
    form_class = CreatePhotoForm
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EditPetPhotoView(UpdateView):
    model = PetPhoto
    template_name = 'main/photo_edit.html'
    form_class = EditPhotoForm


class DeletePetPhotoView(DeleteView):
    model = PetPhoto
    template_name = 'main/photo_delete.html'

workshop/petstagram/templates/main/401.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container mb-5 mt-2">
        <div class="jumbotron">
            <img style="width: 100%"
                 src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
            <div class="position-sticky">
                <h1 class="display-4">401 Unauthorized</h1>
                <p class="lead">You should create a profile to open this page!</p>
                <hr class="my-4">
                <div class="row col-lg-6">

                    <!-- Button to show when profile is NOT created -->
                    <a href="{% url 'create profile' %}" class="btn btn-lg btn-secondary">Create Profile</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

workshop/petstagram/templates/main/dashboard.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block page_content %}
    {% if pets %}
        <!-- If there are pet photos -->
        <h1 class='text-center'>All Pet Photos</h1>
        <div class="container mb-5">
            <div class="row mb-5">
                {% for pet_photo in pets %}
                    <!-- Card with Info for the Pet -->
                    <div class="card ml-3 mb-3" style="width: 18rem;">
                        <!-- Image -->
                        <img src="{{ pet_photo.photo.url }}"
                             class="card-img-top" alt="Photo description">
                        <div class="card-body">
                            {% for pet in pet_photo.tagged_pets.all %}
                                <!-- Info for each pet on the photo -->
                                <h5 class="card-title">{{ pet.name }} {% if pet.birth_date %}, age:
                                    {{ pet.birth_date|years_to_now }}{% endif %}</h5>
                            {% endfor %}
                            <!-- First 30 chars from the description -->
                            <p class="card-text">{{ pet_photo.description| truncatechars:30 }}</p>
                            <!-- Button to the Photo Details Page -->
                            <a href="{% url 'pet photo details' pet_photo.id %}" class="btn btn-primary">See details</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <!-- If there are NO pet photos -->
        <h1 class='text-center'>No pet photos yet</h1>
        <div class=" row d-flex justify-content-center align-content-center">
            <!-- Button to Add a new Photo -->
            <a href="{% url 'create pet photo' %}" class="btn btn-lg btn-secondary row align-self-baseline">Add Photo</a>
        </div>
    {% endif %}

    <!-- End Pet Photos -->
{% endblock %}

workshop/petstagram/templates/main/home_page.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="container">
        <div class="jumbotron">
            <img style="width: 100%"
                 src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
            <div class="position-sticky">
                <h1 class="display-4">Welcome to Petstagram</h1>
                <p class="lead">Share your pets photos.</p>
                <hr class="my-4">
                <div class="flex-row">
                    {% if not request.user.is_authenticated %}
                        <!-- Login Button -->
                        <a href="{% url 'auth:login user' %}" class="btn btn-lg btn-secondary">Login</a>

                        <!-- Register Button -->
                        <a href="{% url 'auth:create profile' %}" class="btn btn-lg btn-secondary">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/pet_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Add Photo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Form for Adding Pet -->
            <form method="post" action="../accounts/profile_details.html">
                <div class="form-group">
                    <label for="name">Pet Name</label>
                    <input type="text" class="form-control" name="first_name" placeholder="Enter name"
                           id="name"/>
                </div>
                <div class="form-group">
                    <label for="type_animal" class="col-form-label">Type:
                    <select class="form-select">
                        <option value="first">Cat</option>
                        <option value="second">Dog</option>
                        <option value="third">Mouse</option>
                    </select></label>
                </div>
                <div class="form-group">
                    <label for="age">Day of Birth:</label>
                    <input type="date" class="form-control" name="age" placeholder=""
                           id="age"/>
                </div>

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
            <!-- End Form for Adding Pet -->
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>

</html>

workshop/petstagram/templates/main/pet_create.html
{% extends 'base.html' %}
{% block page_content %}
    <h1 class="text-center">Add Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="container mb-5" action="{% url 'create pet' %}">
                {% csrf_token %}
                {{ form }}
                <!-- Form for Adding a Pet Info -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/pet_delete.html
{% extends 'base.html' %}
{% block page_content %}
    <h1 class="text-center">Delete Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'delete pet' pet.pk %}">
                {% csrf_token %}
                {{ form }}
                <!-- Form for Deleting a Pet Info -->

                <button class="btn btn-danger mt-2" type="submit">Delete</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/pet_edit.html
{% extends 'base.html' %}
{% block page_content %}
    <h1 class="text-center">Edit Your Pet Info</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" action="{% url 'edit pet' pet.pk %}">
                {% csrf_token %}
                <!-- Form for Editing a Pet Info -->
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/photo_create.html
{% extends 'base.html' %}
{% block page_content %}
    <h1 class="text-center">Add a New Pet Photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'create pet photo' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <!-- Form for Adding Photos -->

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/photo_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block page_content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <!-- Image -->
            <img src="{{ pet_photo.photo.url }}"
                 class="w-100 rounded mx-auto d-block" alt="{{ pet_photo.description }}">
        </div>
        <div class="d-inline p-2 w-50">
            <!-- Info for Pet -->
            {% for pet in pet_photo.tagged_pets.all %}
                <div class="d-flex justify-content-around">
                    <h5><u>Type:</u> {{ pet.type }}</h5>
                    <h5><u>Name:</u>{{ pet.name }}</h5>
                    {% if pet.birth_date %}
                        <h5><u>Age:</u> {{ pet.birth_date|years_to_now }}</h5>
                    {% endif %}
                </div>
            {% endfor %}
            <!-- Description -->
            <p class="mt-2">Description: {{ pet_photo.description }}</p>
            <!-- Likes Button -->
            {% if not is_owner %}
                <a href="{% url 'like photo' pet_photo.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            {% endif %}
            <!-- Likes Counter -->
            <p class="mt-2">Likes: {{ pet_photo.likes }}</p>
            <!-- Buttons -->
            {% if is_owner %}
                <a href="{% url 'edit pet photo' pet_photo.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'delete pet photo' pet_photo.id %}" class="btn btn-danger">Delete</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/photo_edit.html
{% extends 'base.html' %}
{% block page_content %}
    <h1 class="text-center">Edit Pet Photo</h1>
    <img src="{{ pet.photo.url }}"
         class="w-50 rounded mx-auto d-block" alt="Photo description">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'pet photo details' pet.pk%}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <!-- Form for Editing a Photo -->
                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

workshop/petstagram/templates/main/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>