workshop/petstagram/petstagram/auth_app/urls.py
from django.urls import path
from django.views.generic import RedirectView

from petstagram.auth_app.views.auth import UserLoginView, UserRegisterView, ProfileDetailsView, EditProfileView, \
    ChangeUserPasswordView

app_name = 'auth'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login user'),
    path('<int:pk>/', ProfileDetailsView.as_view(), name='profile'),
    path('register/', UserRegisterView.as_view(), name='create profile'),
    path('edit/<int:pk>/', EditProfileView.as_view(), name='edit profile'),
    path('edit-password/', ChangeUserPasswordView.as_view(success_url='auth:password_change_done'),
         name='change password'),
    # path('edit-password/',ChangeUserPasswordView.as_view(),name='change password'),
    # path('password_change_done/',RedirectView.as_view(url='dashboard'))
]

workshop/petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.main.urls')),
    path('accounts/', include('petstagram.auth_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

workshop/petstagram/templates/base.html
{% load profiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% has_profile as hp %}

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

                <li class="nav-item">
                    <!-- Link to Home Page -->
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <!-- Link to Dashboard Page -->
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard </a>
                </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create pet' %}">Add Pet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create pet photo' %}">Add Photo</a>
                </li>
                <li class="nav-item">
                    <!-- Link to Profile Page -->
                    <a class="nav-link" href="{% url 'auth:profile' request.user.id %}">Profile</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!-- End Navigation Bar -->

<div class="container">
    {% block page_content %}
    {% endblock %}
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>